In [1]:
import os
from pathlib import Path

os.chdir("../")

# Download Prices

In [2]:
from src.downloadPrices import DownloadPrices

dp = DownloadPrices(verbose=True)

## get_tickers

In [5]:
tickers = dp._get_tickers()
tickers = tickers[:5]
tickers

		[INFO] Fetching tickers from: https://en.wikipedia.org/wiki/List_of_S%26P_500_companies
		[INFO] Tickers saved to: artifacts\tickers\tickers.json
		[INFO] Parsed 503 tickers.

['MMM', 'AOS', 'ABT', 'ABBV', 'ACN']

## download tickers

In [4]:
dp._download_tickers(tickers)

	[INFO] Downloading 5 tickers from 2015-01-01...

[*********************100%***********************]  5 of 5 completed

	[INFO] Download complete. Dates: 2015-01-01 -> 2026-01-01 | rows=2875
	[INFO] Saved to: artifacts\tickers\prices.parquet

True

In [6]:
from yfinance import download

START_DATE = "2020-01-01"
INTERVAL = "1wk"

df = download(
    tickers=tickers,
    start=START_DATE,
    auto_adjust=False,
    group_by="column",
    progress=True,
    threads=True,
    interval=INTERVAL
)

df

[*********************100%***********************]  5 of 5 completed

Price        Adj Close                                                 \
Ticker            ABBV         ABT         ACN        AOS         MMM
Date
2020-01-01   69.308846   77.227638  186.816971  42.368835  119.274551
2020-01-08   68.770851   77.119690  190.298096  42.288273  121.601051
2020-01-15   69.534004   81.051331  191.598953  42.091339  120.273544
2020-01-22   66.199150   80.879700  193.342087  40.721710  111.014481
2020-01-29   66.665413   79.696411  195.447998  38.304737  105.422874
...                ...         ...         ...        ...         ...
2025-12-10  223.669998  126.860001  272.040009  67.940002  163.199997
2025-12-17  228.789993  124.540001  270.769989  67.739998  160.149994
2025-12-24  229.740005  125.779999  270.000000  67.739998  161.169998
2025-12-31  223.929993  127.779999  275.929993  68.650002  166.210007
2026-01-07  220.899994  125.245003  279.364990  69.930000  164.839996

Price            Close                                                 ...  \
Ticker            ABBV         ABT         ACN        AOS         MMM  ...
Date                                                                   ...
2020-01-01   88.889999   85.860001  203.929993  47.330002  148.745819  ...
2020-01-08   88.199997   85.739998  207.729996  47.240002  151.647156  ...
2020-01-15   87.989998   89.730003  209.149994  47.020000  149.991638  ...
2020-01-22   83.769997   89.540001  210.240005  45.490002  138.444809  ...
2020-01-29   84.360001   88.230003  212.529999  42.790001  131.471573  ...
...                ...         ...         ...        ...         ...  ...
2025-12-10  223.669998  126.860001  272.040009  67.940002  163.199997  ...
2025-12-17  228.789993  124.540001  270.769989  67.739998  160.149994  ...
2025-12-24  229.740005  125.779999  270.000000  67.739998  161.169998  ...
2025-12-31  223.929993  127.779999  275.929993  68.650002  166.210007  ...
2026-01-07  220.899994  125.245003  279.364990  69.930000  164.839996  ...

Price             Open                                                 \
Ticker            ABBV         ABT         ACN        AOS         MMM
Date
2020-01-01   89.080002   86.059998  210.860001  47.910000  148.561874
2020-01-08   89.150002   86.239998  204.000000  47.419998  148.829437
2020-01-15   88.180000   86.110001  208.000000  47.080002  151.688965
2020-01-22   88.029999   90.779999  210.199997  47.320000  150.091980
2020-01-29   83.800003   89.610001  210.679993  45.610001  139.088623
...                ...         ...         ...        ...         ...
2025-12-10  225.000000  121.260002  268.380005  66.660004  164.580002
2025-12-17  223.880005  126.750000  272.649994  67.489998  162.190002
2025-12-24  229.460007  124.010002  270.029999  67.800003  160.110001
2025-12-31  229.740005  125.879997  269.739990  67.540001  161.169998
2026-01-07  225.240005  128.449997  276.010010  68.809998  165.850006

Price         Volume
Ticker          ABBV       ABT       ACN       AOS       MMM
Date
2020-01-01  25656800  18755800  10172000   3933000  12246561
2020-01-08  41965300  31129700  11456900   7495800  15082039
2020-01-15  39237600  23750800   9949300   8797600  13981120
2020-01-22  54367500  30944200   9782400  16352000  24761744
2020-01-29  48838500  23657000   9453300  11336400  28381917
...              ...       ...       ...       ...       ...
2025-12-10  30751200  30351700  20172400   5873100  13693600
2025-12-17  37412800  41329200  26774000   6089600  13123700
2025-12-24   9489800  13492700   7013200   2860200   5578800
2025-12-31  25026700  23047300  14491200   4545400   8912200
2026-01-07  20947752  11985301  10510186   3236732   5761582

[315 rows x 30 columns]

In [9]:
import pandas as pd

df = pd.read_parquet(Path(os.getenv("TICKERS_DIR")) / Path("prices.parquet"))
df = df[df.TICKER == "AAPL"]
print(df.head(10))

           TICKER  ADJ_CLOSE      CLOSE       HIGH        LOW       OPEN  \
DATE
2015-01-01   AAPL  23.887280  26.937500  27.860001  26.157499  27.847500
2015-01-08   AAPL  24.341743  27.450001  28.312500  27.125000  27.307501
2015-01-15   AAPL  24.286320  27.387501  27.764999  26.299999  27.500000
2015-01-22   AAPL  25.563269  28.827499  29.530001  27.257500  27.565001
2015-01-29   AAPL  26.505455  29.889999  30.127501  28.889999  29.080000
2015-02-05   AAPL  27.684855  31.219999  31.230000  29.607500  30.004999
2015-02-12   AAPL  28.648775  32.180000  32.220001  31.392500  31.514999
2015-02-19   AAPL  28.664351  32.197498  33.400002  32.012501  32.119999
2015-02-26   AAPL  28.608707  32.134998  32.717499  31.652500  32.197498
2015-03-05   AAPL  27.206543  30.559999  32.392502  30.527500  32.145000

                  VOLUME
DATE
2015-01-01  8.935724e+08
2015-01-08  1.115053e+09
2015-01-15  9.480124e+08
2015-01-22  1.591688e+09
2015-01-29  1.411946e+09
2015-02-05  1.041652e+09
2015-02-12  9.471632e+08
2015-02-19  1.204899e+09
2015-02-26  1.083526e+09
2015-03-05  1.422733e+09

Se descarga correctamente

## main

In [2]:
from src.downloadPrices import DownloadPrices

DownloadPrices(verbose=True).main()

[START] Download prices
	[RUNNING] get_tickers()
		[INFO] Fetching tickers from: https://en.wikipedia.org/wiki/List_of_S%26P_500_companies
		[INFO] Tickers saved to: artifacts\tickers\tickers.json
		[INFO] Parsed 503 tickers.
	[DONE] get_tickers()
	[RUNNING] download_tickers()
		[INFO] Downloading 503 tickers from 2015-01-01...

[*********************100%***********************]  503 of 503 completed

		[INFO] Download complete. Dates: 2015-01-01 -> 2026-01-12 | rows=573420
		[INFO] Saved to: artifacts\tickers\prices_raw.parquet
	[DONE] download_tickers()
	[RUNNING] verify_coverage()
		[INFO] loading prices: artifacts\tickers\prices_raw.parquet
		[INFO] loading tickers: artifacts\tickers\tickers.json
		[INFO] minimum coverage: 40
		[INFO] tickers to check: 503
		[INFO] writing filtered prices: artifacts\tickers\prices.parquet
		[INFO] rows kept: 280066
		[INFO] tickers kept: 502
	[DONE] verify_coverage()
[FINISHED] Download prices

In [3]:
import pandas as pd

df = pd.read_parquet(Path(os.getenv("TICKERS_DIR")) / Path("prices.parquet"))
df.head(10)

,TICKER,ADJ_CLOSE,CLOSE,HIGH,LOW,OPEN,VOLUME
DATE,,,,,,,
2015-01-01,A,36.180454,39.700001,41.310001,39.020000,41.180000,9011300.0
2015-01-01,AAPL,23.887278,26.937500,27.860001,26.157499,27.847500,893572400.0
2015-01-01,ABBV,42.755795,66.930000,67.050003,63.700001,65.440002,26860500.0
2015-01-01,ABT,36.305115,44.759998,45.450001,43.930000,45.250000,20146300.0
2015-01-01,ACGL,18.577387,19.536667,19.860001,19.333332,19.733334,4879200.0
2015-01-01,ACN,73.993546,88.529999,90.089996,86.010002,89.669998,10753800.0
2015-01-01,ADBE,71.110001,71.110001,73.199997,69.879997,72.699997,10026200.0
2015-01-01,ADI,42.972912,53.810001,56.250000,53.029999,55.680000,6198900.0
2015-01-01,ADM,36.179176,49.970001,52.599998,48.939999,52.200001,13573000.0
2015-01-01,ADP,65.539001,83.260002,84.440002,81.800003,82.980003,9786200.0